Bài tập trên lớp

In [ ]:
import numpy as np
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print (x)

[ 18 -11   9  -8]


In [ ]:
x = 0.5*(2*u-v-3*w)
print (x)

[ 9.  -5.5  4.5 -4. ]


In [ ]:
from numpy import linalg
A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print(X)

[ 1. -2. -1.]


In [ ]:
A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
from numpy import linalg as LA
#a1 = LA.inv(A)   => LinAlgError: Singular matrix
#a2 = LA.inv(B)   => LinAlgError: Singular matrix
a3 = LA.inv(A+B)
a4 = LA.det(A)
a5 = LA.det(B)
a6 = LA.det(A+B)
print(a3)
print(a4)
print(a5)
print(a6)

[[1. 0.]
 [0. 1.]]
0.0
0.0
1.0


In [ ]:
import sympy as sp
x, y = sp.symbols('x y')
A = sp.Matrix([[x, y],[y, x]])
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
A1.T

Matrix([
[x1, y1],
[y1, x1]])

In [ ]:
(A1+A2).T

Matrix([
[x1 + x2, y1 + y2],
[y1 + y2, x1 + x2]])

In [ ]:
((A1+A2).T).equals(A1+A2)

True

In [ ]:
c = sp.symbols('c')
print (c*A)

Matrix([[c*x, c*y], [c*y, c*x]])


In [ ]:
((c*A).T).equals(c*A)

True

In [ ]:
import numpy as np
u = np.array([1, 2, 3])
v = np.array([0, 1, 2])
w = np.array([-1, 0, 1])
A = np.column_stack((u, v, w))
a = np.array([1, 1, 1])
x1 = np.linalg.lstsq(A, a, rcond=None)
print(x1[0])
print(np.allclose(A @ x1[0], a))
b = np.array([1, -2, 2])
x2 = np.linalg.lstsq(A, b, rcond=None)
print(x2[0])
print(np.allclose(A @ x2[0], b))

[ 5.0000000e-01  1.2490009e-16 -5.0000000e-01]
True
[0.08333333 0.16666667 0.25      ]
False


In [ ]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1-2*c3, 2*c1+c2, 3*c1+2*c2+c3], [c1, c2, c3])

{c1: 0, c2: 0, c3: 0}

In [ ]:
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}

In [ ]:
u1 = 0
u2 = 0
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: 0, c2: 0}

In [ ]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T
print (P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [ ]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0], [0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print (P_caub)

[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [ ]:
vecdelta = np.array([6, 0])
matran_c = np.array([[-1, 0], [ 0, 1]])
P_cauc = (P.T @ matran_c + vecdelta).T
print(P_cauc)

[[6 6 3 3 5 5 4 4 5 5]
 [0 5 5 4 4 3 3 2 2 0]]


In [ ]:
L = 0.5
M = 0
vecdelta = np.array([1, 1])
matran_d = np.array([[1, L], [M, 1]])
P_caud = (P.T @ matran_d + vecdelta).T
print(P_caud)

[[1.  1.  4.  4.  2.  2.  3.  3.  2.  2. ]
 [1.  6.  7.5 6.5 5.5 4.5 5.  4.  3.5 1.5]]


In [ ]:
mat_y0 = np.array([[1, 0], [0, -1]])
P_y0 = (P.T @ mat_y0).T
print(P_y0)

[[ 0  0  3  3  1  1  2  2  1  1]
 [ 0 -5 -5 -4 -4 -3 -3 -2 -2  0]]


In [ ]:
mat_yx = np.array([[0, 1], [1, 0]])
P_yx = (P.T @ mat_yx).T
print(P_yx)

[[0 5 5 4 4 3 3 2 2 0]
 [0 0 3 3 1 1 2 2 1 1]]


In [ ]:
import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c')
d, e, f = sp.symbols('d e f')
f1(a, b, c)

a - b + c

In [ ]:
f1(d, e, f)

d - e + f

In [ ]:
f1(a+d, b+e, c+f)

a - b + c + d - e + f

In [ ]:
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)

True

In [ ]:
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f))

True

In [ ]:
q = sp.symbols('q')
(q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand())

True

In [ ]:
bieuthuc2 = 2*x2 + 3* x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
(q*f2(a,b,c) + f2(d,e,f)).equals(f2(q*a+d, q*b+e, q*c+f).expand())

True

In [ ]:
import numpy as np
A = np.array([[1, 3], [2, 5]])
b = np.array([4, 5])
x = np.linalg.solve(A, b)
S, T = x
print("S =", S, "T =", T)
f_v1 = np.array([1, 1, 2])
f_v2 = np.array([4, 2, 1])
f_v = S * f_v1 + T * f_v2
print("f(v) =", f_v)

S = -5.0 T = 3.0
f(v) = [ 7.  1. -7.]


In [ ]:
import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
fu1 = np.array([1,1,2])
fu2 = np.array([4,2,1])
fu = a*fu1 + b*fu2
print (fu)

[a + 4*b a + 2*b 2*a + b]


In [ ]:
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2
print (fu)

[3*x - y -x + y -8*x + 5*y]


In [ ]:
x1, x2, x3 = sp.symbols('x1 x2 x3')
sp.solve([x1+x2-x3, 2*x1+3*x2-x3, 3*x1+5*x2-x3],[x1, x2, x3])

{x1: 2*x3, x2: -x3}

In [ ]:
import numpy as np
v1 = np.array([-1, 1])
v2 = np.array([1, 0])
w1 = np.array([1, 2])
w2 = np.array([1, 3])
def f(xy):
    x, y = xy
    return np.array([x - y, x])
fv1 = f(v1)
fv2 = f(v2)
print(fv1)
print(fv2)
D = np.column_stack((w1, w2))
coords1 = np.linalg.solve(D, fv1)
coords2 = np.linalg.solve(D, fv2)
print(coords1)
print(coords2)
A = np.column_stack((coords1, coords2))
print(A)


[-2 -1]
[1 1]
[-5.  3.]
[ 2. -1.]
[[-5.  2.]
 [ 3. -1.]]


In [ ]:
import numpy as np
import math
from scipy import linalg as LA
B = np.matrix([[1.0/math.sqrt(2), 1.0/math.sqrt(2)], [-1.0/math.sqrt(2),1.0/math.sqrt(2)]])
LA.orth(B)

array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])

In [ ]:
1.0/math.sqrt(2)

0.7071067811865475

Bài tập chương

Bài 1

In [1]:
from sympy import symbols, Matrix

x, y, z = symbols('x y z')
gu = Matrix([x + y, z + 2, 0])
print(gu)
gv = Matrix([2*x + 2*y, 2*z + 4, 0])
print(gv)
g_u_v = Matrix([(x + x + y + y), (z + z + 2 + 2), 0])
print(g_u_v)
la_tuyen_tinh = False
print(la_tuyen_tinh)

Matrix([[x + y], [z + 2], [0]])
Matrix([[2*x + 2*y], [2*z + 4], [0]])
Matrix([[2*x + 2*y], [2*z + 4], [0]])
False


Bài 2

In [3]:
import numpy as np
P = np.array([[0, 1], [1, -1]])
F = np.array([[1, 2, 3], [4, 5, 6]])  # ví dụ tập điểm
bien_doi_F = P @ F
print(bien_doi_F)

[[ 4  5  6]
 [-3 -3 -3]]


Bài 3

In [4]:
import sympy as sp
v1, v2 = sp.symbols('v1 v2')
a, b = sp.symbols('a b')
u1, u2 = sp.symbols('u1 u2')
v1a, v2a = sp.symbols('v1a v2a')
Tu = (u1 - u2, u1 + 2*u2)
Tv = (v1a - v2a, v1a + 2*v2a)
print(Tu)
print(Tv)
T_ab_uv = (a*u1 + b*v1a - (a*u2 + b*v2a), a*u1 + b*v1a + 2*(a*u2 + b*v2a))
print(T_ab_uv)
T_linear_comb = (a*Tu[0] + b*Tv[0], a*Tu[1] + b*Tv[1])
print(T_linear_comb)
kiem_tra_T = sp.simplify(sp.Matrix(T_ab_uv) - sp.Matrix(T_linear_comb)) == sp.Matrix([0, 0])
print(kiem_tra_T)

(u1 - u2, u1 + 2*u2)
(v1a - v2a, v1a + 2*v2a)
(a*u1 - a*u2 + b*v1a - b*v2a, a*u1 + 2*a*u2 + b*v1a + 2*b*v2a)
(a*(u1 - u2) + b*(v1a - v2a), a*(u1 + 2*u2) + b*(v1a + 2*v2a))
True


Bài 4

In [6]:
A = np.array([[13, -5], [-5, 13]])
from numpy import linalg as LA
import math
gt, vt = LA.eig(A)
P = vt
A_cheo = P.T @ A @ P
print(A_cheo)
kiem_tra_truc_giao = np.allclose(P.T @ P, np.eye(2))
print(kiem_tra_truc_giao)
theta = math.atan2(P[1, 0], P[0, 0]) * 180 / math.pi
print(round(theta, 2))
print(gt)

[[ 1.8000000e+01  0.0000000e+00]
 [-8.8817842e-16  8.0000000e+00]]
True
-45.0
[18.  8.]
