Bài tập trên lớp

Bài 1

In [2]:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b)
C = np.asmatrix(np.random.random( (10,5) ) )
D = np.asmatrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1)
print(A)
print(B)
print(C)
print(D)
print(F)

[[0.76933265 0.80954949]
 [0.18571842 0.98876857]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.78777938 0.94846842 0.06210193 0.51506202 0.33515976]
 [0.10035239 0.99481928 0.82407255 0.70988573 0.39196225]
 [0.87820633 0.6896932  0.74382004 0.5521479  0.04477338]
 [0.97134319 0.16016547 0.63982634 0.64342818 0.14600753]
 [0.05803497 0.21178687 0.62772849 0.44883108 0.05166033]
 [0.05943382 0.25543643 0.1016817  0.26286549 0.6442005 ]
 [0.48709442 0.47350674 0.41784751 0.09712425 0.44799788]
 [0.38950666 0.2853873  0.30808762 0.53887321 0.51132138]
 [0.82455942 0.17845011 0.84325416 0.01547713 0.18351501]
 [0.24457888 0.68192604 0.07813161 0.73745378 0.35485054]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [3]:
F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
F = np.eye(3, k=-1)
print(F)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [5]:
np.linalg.matrix_rank(C)

np.int64(5)

In [6]:
A.I

matrix([[ 1.62001932, -1.326383  ],
        [-0.30428499,  1.26049088]])

In [7]:
linalg.inv(A)

array([[ 1.62001932, -1.326383  ],
       [-0.30428499,  1.26049088]])

In [8]:
linalg.det(A)

np.float64(0.6103436883885593)

In [9]:
A.T

matrix([[0.76933265, 0.18571842],
        [0.80954949, 0.98876857]])

In [10]:
A.H

matrix([[0.76933265, 0.18571842],
        [0.80954949, 0.98876857]])

In [11]:
linalg.solve(A, b)

array([[ 1.62001932+9.27464189j,  0.        -3.39187634j,
         0.        -3.09824002j],
       [-0.30428499+2.30339862j,  0.        +5.6938844j ,
         0.        +6.65009029j]])

In [13]:
E = np.asmatrix(a).T
print(E)

[[1]
 [2]
 [3]]


In [14]:
linalg.lstsq(F, E)

(array([[2.],
        [3.],
        [0.]]),
 array([], dtype=float64),
 2,
 array([1., 1., 0.]))

In [15]:
np.add(A, D)

matrix([[4.76933265, 3.80954949],
        [2.18571842, 6.98876857]])

In [16]:
np.subtract(A, D)

matrix([[-3.23066735, -2.19045051],
        [-1.81428158, -5.01123143]])

In [17]:
np.divide(A, D)

matrix([[0.19233316, 0.26984983],
        [0.09285921, 0.16479476]])

In [18]:
A @ D

matrix([[4.69642958, 7.16529489],
        [2.72041082, 6.48976666]])

In [19]:
np.multiply(D, A)

matrix([[3.0773306 , 2.42864847],
        [0.37143684, 5.9326114 ]])

In [20]:
np.dot(A, D)

matrix([[4.69642958, 7.16529489],
        [2.72041082, 6.48976666]])

In [21]:
np.vdot(A, D)

matrix([[3.0773306]])

In [22]:
linalg.expm(A)

array([[2.3353569 , 2.00309325],
       [0.45952881, 2.87831396]])

In [23]:
linalg.logm(A)

array([[-0.38172433,  0.99504283],
       [ 0.22827237, -0.11200872]])

Bài 2

In [24]:
import numpy as np
A = np.array([ [0,1], [1,0]])
print(A)

[[0 1]
 [1 0]]


In [25]:
temp = A.dot(A)
print(temp)

[[1 0]
 [0 1]]


In [26]:
k= 6
for i in range(k-1):
 temp = temp.dot(A)
 print (temp)
 print('---')

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


In [27]:
B = np.array([ [0,-1], [-1,0]])
print(B)

[[ 0 -1]
 [-1  0]]


In [28]:
temp = B.dot(B)
print(temp)

[[1 0]
 [0 1]]


In [29]:
k= 5
for i in range(k-1):
 temp = temp.dot(B)
 print (temp)
 print('---')

[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


In [30]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [31]:
temp = C.dot(C)
print(temp)

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [32]:
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp)

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]


In [33]:
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M)
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [35]:
MM = M.dot(M)
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [36]:
for i in range(100):
 MM = MM.dot(M)
print (MM)

[[0.6 0.6]
 [0.4 0.4]]


Bài 3

In [37]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M)
print (P)

[[1. 0.]
 [0. 1.]]


In [38]:
print (L)

[[1.   0.  ]
 [0.25 1.  ]]


In [39]:
print (U)

[[0.8   0.3  ]
 [0.    0.625]]


In [40]:
L.dot(U)

array([[0.8, 0.3],
       [0.2, 0.7]])

In [41]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A)
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [42]:
temp = temp.dot(A)
print(temp)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [43]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
 temp = temp.dot(A)
 sumA = sumA + temp
print (temp)
print (sumA)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


Bài tập chương 3

Bài tập 1

In [47]:
import numpy as np
#a
A = np.array([[2, 1, 3], [1, 1, 1], [1, 2, 1]])
det_A = np.linalg.det(A)
if det_A == 0:
  print ("Không khả nghịch")
else:
    print("Khả nghịch. Định thức:", det_A)
    A_inv = np.linalg.inv(A)
    print("Nghịch đảo:\n", A_inv)
#b
t = input("Nhập họ và tên hoặc mã số sinh viên: ")
#c
cd = [ord(char) for char in t]
while len(cd) % 3 != 0:
  cd.append(0)
pt = np.array(cd).reshape(-1, 3)
mh = np.dot(pt, A.T)
print("Sau khi mã hóa:\n", mh)
#d
gm=np.dot(mh, A_inv.T)
sgm=np.rint(gm).astype(int)
kq = ''.join(chr(num) for num in sgm.flatten() if num != 0)
print("Sau khi giải mã:\n", kq)

Khả nghịch. Định thức: 0.9999999999999996
Nghịch đảo:
 [[-1.00000000e+00  5.00000000e+00 -2.00000000e+00]
 [ 1.48029737e-16 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -3.00000000e+00  1.00000000e+00]]
Nhập họ và tên hoặc mã số sinh viên: 2474802010209
Sau khi mã hóa:
 [[317 157 209]
 [304 156 212]
 [295 147 195]
 [290 146 196]
 [114  57  57]]
Sau khi giải mã:
 2474802010209


In [50]:
import numpy as np
def pslt(c_list):
    M = np.array([[1, 0], [0, 1]])
    for c in c_list:
        A = np.array([[c, 1], [1, 0]])
        M = M @ A
    kq = M @ np.array([1, 0])
    p_n, q_n = kq[0], kq[1]
    return p_n, q_n
c_list = [3, 1, 2]
p, q = pslt(c_list)
print(f"Kết quả: {p}/{q} = {p/q}")

Kết quả: 11/3 = 3.6666666666666665


In [ ]:
#Công thức tính (pn, qn) bằng cách nhân các ma trận liên tiếp đúng theo quy nạp và khớp với biểu diễn của phân số từ liên phân số.