Bài tập trên lớp

Bài 1

In [ ]:
def scale(a, v):
    return [a*vi for vi in v]
v = [3,5,7]
print(scale(2, v))

[6, 10, 14]


In [ ]:
def sumvector(v, w):
    return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [3,4,6]
print(sumvector(v, w))


[6, 9, 13]


In [ ]:
def dotvector(v, w):
    return sum(vi*wi for (vi, wi) in zip(v, w))
print(dotvector(v, w))

71


In [ ]:
def lenvector(v):
    return dotvector(v,v)
print(lenvector(v))

83


Bài 2

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print(scores)
print(scores >= 0)
print(scores < 0)
print(np.select([scores >=0, scores < 0],['so duong', 'so am'], default=""))

[-1  1  2 -3  5 -4]
[False  True  True False  True False]
[ True False False  True False  True]
['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


In [ ]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print(np.select([scores >0, scores < 0],['so duong', 'so am'], default="so 0"))

['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


Bài 3

In [ ]:
import numpy as np
from scipy import linalg, sparse
D = np.asmatrix([ [3,4], [5,6] ])
print(D)

[[3 4]
 [5 6]]


In [ ]:
C = np.asmatrix(np.random.random((5,7)))
print(C)

[[0.23220887 0.54871787 0.95325198 0.66914534 0.73836586 0.49881215
  0.7836818 ]
 [0.96729376 0.09953563 0.98908335 0.91392434 0.24318924 0.72323646
  0.59021607]
 [0.79556237 0.1911262  0.05256136 0.1091827  0.00953566 0.06351733
  0.28935566]
 [0.45855582 0.66612209 0.42134593 0.53681468 0.83736661 0.78008373
  0.98884417]
 [0.41546643 0.48043376 0.37091972 0.16657105 0.4357281  0.28608486
  0.09424704]]


In [ ]:
A = np.asmatrix(np.random.random((2,2)))
print(A)

[[0.36070621 0.62563171]
 [0.28592286 0.17321998]]


In [ ]:
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B = np.asmatrix(b)
print(b)
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [ ]:
print(A.T)

[[0.36070621 0.28592286]
 [0.62563171 0.17321998]]


In [ ]:
print(A.I)

[[-1.48813292  5.3748021 ]
 [ 2.45636332 -3.09882707]]


In [ ]:
print(linalg.inv(A))
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
print(M)
M_lower = np.tril(M)
print(M_lower)

[[-1.48813292  5.3748021 ]
 [ 2.45636332 -3.09882707]]
[[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [ ]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
print(M)

[[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]


In [ ]:
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [ ]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M)
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag)

[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [ ]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
print(sp.solve([x * x + 2 - 6, y - 1 - 6, x + z - 1, 2 * x * x - 8, z * z + 4 - 5, y - z - 8], [x, y, z]))

[(2, 7, -1)]


In [ ]:
x = [1, 2, 3]
y = [1, 2, 3]
print(all([x[i] == y[i] for i in range(len(x))]))
y = [1, 2, 4]
print(all([x[i] == y[i] for i in range(len(x))]))

True
False


In [ ]:
import numpy as np
print(np.array_equal([1, 2], [1, 2]))
print(np.array_equal(np.array([1, 2]), np.array([1, 2])))

True
True


In [ ]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [ ]:
I6 = np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
print(A.size)

36


In [ ]:
print(np.matrix.diagonal(A) )

[ 0.  7. 14. 21. 28. 35.]


In [ ]:
A = A + I6
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [ ]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print (C)

[ 71. 198. 325. 452. 579. 706.]


In [ ]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


In [ ]:
E = A.dot(D.T)
print(E)

[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [ ]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print(F)
print(G)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [ ]:
print(np.linalg.inv(A))

[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]


In [ ]:
print(np.linalg.inv(np.linalg.inv(A)))

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


Bài 4

In [ ]:
import numpy as np
A = np.array([[1,1], [1,0]])
b = np.array([1, 0])
n = 10
for i in range(n):
 b = A.dot(b)
 print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


Bài 5

In [ ]:
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [ ]:
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
A_nghichdao = np.linalg.inv(A)
print(A_nghichdao)

LinAlgError: Singular matrix

In [ ]:
#Lỗi do det(A) = 0
#Nên ma trận A không tồn tại ma trạn nghịch đảo

Bài tập chương 2

Bài tập 1

In [ ]:
import numpy as np

In [ ]:
A1 = np.array([[1, -1], [2, 3]])
b1 = np.array([-2, 6])
x1 = np.linalg.solve(A1, b1)
print("Vấn đề 1: Giao điểm của 2 đường thẳng:\n", x1)

Vấn đề 1: Giao điểm của 2 đường thẳng:
 [0. 2.]


In [ ]:
A2 = np.array([[1, -1, 0], [2, 0, -1], [1, 1, 1]])
b2 = np.array([2, 3, 6])
x2 = np.linalg.solve(A2, b2)
print("Vấn đề 2: Giao điểm 3 mặt phẳng:\n", x2)

Vấn đề 2: Giao điểm 3 mặt phẳng:
 [2.75 0.75 2.5 ]


In [ ]:
A3 = np.array([[1, 1, 1], [4, 2, 1], [9, 3, 1]])
b3 = np.array([4, 3, 4])
x3 = np.linalg.solve(A3, b3)
print("Vấn đề 3: Hệ số a, b, c của đa thức:\n", x3)

Vấn đề 3: Hệ số a, b, c của đa thức:
 [ 1. -4.  7.]


In [ ]:
A4 = np.array([[1, 0, 1], [1, 1, -2], [-2, 1, 1]])
b4 = np.array([1, -3, 0])
x4 = np.linalg.solve(A4, b4)
print("Vấn đề 4: Hệ số a, b, c sau phân tích phân thức:\n", x4)

Vấn đề 4: Hệ số a, b, c sau phân tích phân thức:
 [-0. -1.  1.]


Bài tập 2

In [ ]:
from sympy import symbols, Eq, solve
x, y = symbols('x y')
z = symbols('z')
a, b, c = symbols('a b c')

In [ ]:
eq1 = Eq(x - y, -2)
eq2 = Eq(2*x + 3*y, 6)
sol1 = solve((eq1, eq2), (x, y))
print("Vấn đề 1: Giao điểm của 2 đường thẳng:\n", sol1)

Vấn đề 1: Giao điểm của 2 đường thẳng:
 {x: 0, y: 2}


In [ ]:
eq1 = Eq(x - y, 2)
eq2 = Eq(2*x - z, 3)
eq3 = Eq(x + y + z, 6)
sol2 = solve((eq1, eq2, eq3), (x, y, z))
print("Vấn đề 2: Giao điểm 3 mặt phẳng:\n", sol2)

Vấn đề 2: Giao điểm 3 mặt phẳng:
 {x: 11/4, y: 3/4, z: 5/2}


In [ ]:
eq1 = Eq(a + b + c, 4)
eq2 = Eq(4*a + 2*b + c, 3)
eq3 = Eq(9*a + 3*b + c, 4)
sol3 = solve((eq1, eq2, eq3), (a, b, c))
print("Vấn đề 3: Hệ số a, b, c của đa thức:\n", sol3)

Vấn đề 3: Hệ số a, b, c của đa thức:
 {a: 1, b: -4, c: 7}


In [ ]:
eq1 = Eq(a + c, 1)
eq2 = Eq(a + b - 2*c, -3)
eq3 = Eq(-2*a + b + c, 0)
sol4 = solve((eq1, eq2, eq3), (a, b, c))
print("Vấn đề 4: Hệ số a, b, c sau phân tích phân thức:\n", sol4)

Vấn đề 4: Hệ số a, b, c sau phân tích phân thức:
 {a: 0, b: -1, c: 1}


Bài tập 3

In [ ]:
import numpy as np
F = np.array([[1, 1], [1, 0]])
def tinh_luy_thua_fibonacci(k):
  return np.linalg.matrix_power(F, k)
k = int(input("Nhập k: "))
Fk = tinh_luy_thua_fibonacci(k)
print(Fk)

Nhập k: 5
[[8 5]
 [5 3]]
