Bài tập trên lớp

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print (tich)

32


In [ ]:
np.dot(a,b)

np.int64(32)

In [ ]:
import numpy as np
a = np.array([1,2,-3])
np.linalg.norm(a)

np.float64(3.7416573867739413)

In [ ]:
np.linalg.norm(a, 2)

np.float64(3.7416573867739413)

In [ ]:
a = np.array([1,2,-3])
np.linalg.norm(a,1)

np.float64(6.0)

In [ ]:
def chuan(v,k):
 tong = 0
 for i in range(len(v)):
  tong = tong + abs(v[i]**k)
 ketqua = math.pow(tong, 1.0/k)
 return ketqua

In [ ]:
import math
import numpy as np
a = np.array([1,2,-3])
chuan(a, 1)

6.0

In [ ]:
np.linalg.norm(a,1)

np.float64(6.0)

In [ ]:
chuan(a, 2)

3.7416573867739413

In [ ]:
np.linalg.norm(a,2)

np.float64(3.7416573867739413)

In [ ]:
chuan(a, 3)

3.3019272488946263

In [ ]:
np.linalg.norm(a,3)

np.float64(3.3019272488946263)

In [ ]:
chuan(a, 1000)

1.0442214818467515

In [ ]:
np.linalg.norm(a,1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

In [ ]:
from scipy import linalg
linalg.norm(a)

np.float64(3.7416573867739413)

In [ ]:
linalg.norm(a, 100)

np.float64(3.0)

In [ ]:
linalg.norm(a, 1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

In [ ]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
MT

array([[ 5,  4, -4, -9],
       [-4,  3, -3,  8],
       [ 3, -2, -1,  6]])

In [ ]:
v = (1.0/m)*MT.dot(mi)

In [ ]:
print (v)

[1.3 0.9 0. ]


In [ ]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [ ]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)

In [ ]:
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [ ]:
print (sympy.pretty(nghiem))

[-7, 3]


In [ ]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P)
print (P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [ ]:
A.dot(P)

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [ ]:
P .dot(D)

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [ ]:
P @ (D ** 1000) @ P1

array([[ 5.03503397e+18,  3.50482117e+18],
       [ 3.50482117e+18, -4.31115581e+18]])

In [ ]:
print (D **2)

[[49  0]
 [ 0  9]]


Bài tập chương

In [25]:
import numpy as np
a = np.array([1,2,3])
mag = np.sqrt(a.dot(a))
mag = np.sqrt(a @ a )
mag = np.sqrt(np.inner(a,a))
mag = lambda x : math.sqrt(sum(i** 2 for i in x))
mag(a)

3.7416573867739413

In [26]:
import numpy as np
def khoangcach(u, v):
    return np.linalg.norm(u - v)
def goc(u, v):
    dot_product = np.dot(u, v)
    u_bt = np.linalg.norm(u)
    v_bt = np.linalg.norm(v)
    cos_theta = dot_product / (u_bt * v_bt)
    return np.arccos(np.clip(cos_theta, -1.0, 1.0))
def phepchieu(u, v):
    dot_uv = np.dot(u, v)
    dot_vv = np.dot(v, v)
    return (dot_uv / dot_vv) * v
def input_vector(name):
    return np.array(list(map(float, input(f"Nhập vector {name} (cách nhau bởi dấu cách): ").split())))
u = input_vector("u")
v = input_vector("v")
print("\na) Khoảng cách giữa u và v:", khoangcach(u, v))
print("b) Góc giữa u và v (radian):", goc(u, v))
print("   Góc giữa u và v (độ):", np.degrees(goc(u, v)))
print("c) Phép chiếu trực giao của u lên v:", phepchieu(u, v))

Nhập vector u (cách nhau bởi dấu cách): 1 2 3
Nhập vector v (cách nhau bởi dấu cách): 2 4 3

a) Khoảng cách giữa u và v: 2.23606797749979
b) Góc giữa u và v (radian): 0.3394012639700528
   Góc giữa u và v (độ): 19.446259986889597
c) Phép chiếu trực giao của u lên v: [1.31034483 2.62068966 1.96551724]
