Bài 1

In [7]:
import numpy as np
from math import acos, degrees
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1], [0, 3, 4], [2, -1, 0]])
A_plus_B = A + B
expr = 3 * A - 2 * B
print("a) A + B =", A_plus_B)
print("   3A - 2B =", expr)
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
theta_rad = acos(cos_theta)
theta_deg = round(degrees(theta_rad), 3)
print("\nb) A · B =", dot_product)
print("   Góc giữa hai vector (độ) =", theta_deg)
C_transpose = C.T
CtC = np.dot(C_transpose, C)
print("\nc) C^T * C =\n", CtC)

a) A + B = [3 3 1 5]
   3A - 2B = [  4 -11  13 -10]

b) A · B = -8
   Góc giữa hai vector (độ) = 108.376

c) C^T * C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


Bài 2

In [8]:
import numpy as np
M = np.array([[1, 2, 3, 0], [4, 5, 6, 1], [7, 8, 9, 2], [0, 1, 1, 0]])
N = np.array([ [0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
product = np.dot(M, N)
print("a) Tích M × N =\n", product)
try:
    det_M = np.linalg.det(M)
    print("\nb) Định thức của M =", round(det_M, 3))
except np.linalg.LinAlgError:
    print("\nb) Không thể tính định thức vì M không là ma trận vuông.")
rank_N = np.linalg.matrix_rank(N)
print("\nc) Hạng của N =", rank_N)

a) Tích M × N =
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b) Định thức của M = 0.0

c) Hạng của N = 2


Bài 3

In [9]:
import numpy as np
P = np.array([ [2, 1, 0, 1], [0, 3, 1, -1], [1, 0, 4, 2], [0, 1, 0, 3]])
b = np.array([4, 7, 9, 5])
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P:\n", P_inv)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch (không tồn tại nghịch đảo).")
x = np.dot(P_inv, b)
print("\nb) Nghiệm của hệ phương trình [x, y, z, w] =\n", x)
check = np.dot(P, x)
print("\nc) Kiểm tra P * x =\n", check)
print("Vector b =\n", b)
print("So sánh P*x với b:", np.allclose(check, b))

a) Ma trận nghịch đảo của P:
 [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

b) Nghiệm của hệ phương trình [x, y, z, w] =
 [0.46511628 2.10465116 1.65116279 0.96511628]

c) Kiểm tra P * x =
 [4. 7. 9. 5.]
Vector b =
 [4 7 9 5]
So sánh P*x với b: True


Bài 4

In [10]:
import numpy as np
Q = np.array([ [4, -1, 0], [1, 3, -2], [0, 1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("a) Các giá trị riêng của Q:")
print(eigenvalues)
print("\nb) Các vector riêng (theo cột):")
print(eigenvectors)
print("\nc) Vector riêng sau khi chuẩn hóa (độ dài = 1):")
normalized_vectors = []
for vec in eigenvectors.T:
    norm_vec = vec / np.linalg.norm(vec)
    normalized_vectors.append(norm_vec)
    print(norm_vec)

a) Các giá trị riêng của Q:
[3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]

b) Các vector riêng (theo cột):
[[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]

c) Vector riêng sau khi chuẩn hóa (độ dài = 1):
[0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
[-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
[-0.26206044+0.31354813j -0.78166743+0.j         -0.21963176-0.41685708j]


Bài 5

In [11]:
import numpy as np
R = np.array([[1, -2, 3], [2,  0, 1], [-1, 1, 4]])
b = np.array([10, 8, 7])
x = np.linalg.solve(R, b)
print("a) Nghiệm của hệ phương trình R x = b là:\n", x)
det_R = np.linalg.det(R)
print("\nb) Định thức của R =", round(det_R, 3))
if det_R != 0:
    R_inv = np.linalg.inv(R)
    x_inv = np.dot(R_inv, b)
    print("Ma trận nghịch đảo R⁻¹:\n", R_inv)
    print("Nghiệm bằng nghịch đảo:\n", x_inv)
    print("Hai nghiệm giống nhau?", np.allclose(x, x_inv))
else:
    print("Ma trận R không khả nghịch nên không thể dùng nghịch đảo để giải.")
fro_norm = np.linalg.norm(R, ord='fro')
print("\nc) Chuẩn Frobenius của R =", round(fro_norm, 3))

a) Nghiệm của hệ phương trình R x = b là:
 [2.7826087  0.04347826 2.43478261]

b) Định thức của R = 23.0
Ma trận nghịch đảo R⁻¹:
 [[-0.04347826  0.47826087 -0.08695652]
 [-0.39130435  0.30434783  0.2173913 ]
 [ 0.08695652  0.04347826  0.17391304]]
Nghiệm bằng nghịch đảo:
 [2.7826087  0.04347826 2.43478261]
Hai nghiệm giống nhau? True

c) Chuẩn Frobenius của R = 6.083
